version: '3'

networks:
  front-net:
  back-net:
  db-net:

secrets:
  postgresql-secrets:
    file: ./postgre/.env

services:
  postgre:
    container_name: postgre
    image: postgre
    restart: always
    build:
      context: postgre
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_ROOT: "${POSTGRES_ROOT}"
      POSTGRES_ROOT_PASSWORD: "${POSTGRES_ROOT_PASSWORD}"
    volumes:
      - postgresql-volume:/var/lib/postgresql
    secrets:
      - postgresql-secrets
    networks:
      - db-net
  
  golang:
    container_name: golang
    image: golang
    restart: always
    build:
      context: golang
    depends_on:
      - postgre
    networks:
      - db-net
      - front-net
      - back-net

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - golang
      - react-native
    build:
      context: nginx
    volumes:
      - postgresql-volume:/var/lib/postgresql
      - nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front-net
    ports:
      - 443:443

  react-native:
    container_name: react-native
    image: react-native
    restart: always
    depends_on:
      - golang
    build:
      context: react-native
    networks:
      - front-net

volumes:
  postgresql-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /nfs/homes/dapaulin/project-volumes/postgresql
